### ISSUE TITLE
Support for Path Variables

### ISSUE THREAD

**Issue by MrBanja** [darrenburns/posting#111] opened 2024-09-23 11:10 UTC
Hi, you're doing great work with this product!

I’d really appreciate having support for path variables, similar to what Postman offers. Using .env files doesn’t quite fit my use case, as I have different values for different requests in the same session, but with the same path name. While I could create var_1, var_2, etc., in .env, this approach quickly becomes messy and unmanageable.

P.S. It would also be great to have the ability to invoke an editor (F4) for the URL line. That would be a fantastic addition!

**Comment by darrenburns** [comment] 2024-11-18 17:26
Thanks @MrBanja and sorry for the delay. This is a duplicate of https://github.com/darrenburns/posting/discussions/143, so feel free to chime in there with more info/examples of how you use this feature in Postman.

I like the idea and will probably implement the URL line editor.

**Closed by darrenburns** 2024-11-18 17:26 UTC
