### ISSUE TITLE
Entering editor then quitting doesn't render back the whole app

### ISSUE THREAD

**Issue by 11Firefox11** [darrenburns/posting#127] opened 2024-11-10 07:58 UTC
Problem: After viewing something in the editor then quitting the application partially disappears.
Steps to reproduce: Make a request -> navigate to the body -> insprect in editor (f4) -> quit the editor -> the app partially disappeared.
What I use: Linux, tmux, nvim, posting version 2.0.1.

![image](https://github.com/user-attachments/assets/ad4e7d2c-bc30-4d61-bac1-da6594afee6f)
![image](https://github.com/user-attachments/assets/2728548a-3921-460f-a15b-e51f08ee97c3)
![image](https://github.com/user-attachments/assets/fb4c452c-7e0b-442a-9051-d217efdcbc5d)

**Comment by darrenburns** [comment] 2024-11-10 15:30
What terminal do you use?

**Comment by 11Firefox11** [comment] 2024-11-10 16:36
Wezterm. Tried it in xterm too, same issue.

**Comment by darrenburns** [comment] 2024-11-10 18:00
Thanks, I can reproduce this too. Will look into it.

**Comment by 11Firefox11** [comment] 2024-11-10 18:05
Cool! Probably just need to rerender it after and that's it.

**Comment by pedroid999** [comment] 2024-11-18 10:10
Same for me using alacritty with zellij.

**Comment by darrenburns** [comment] 2024-11-18 10:14
What version are you using @pedroid999?

**Comment by pedroid999** [comment] 2024-11-18 10:29
Now i update to 2.2.0 release and seem work fine though when edit json body and come back from neovim with :wq add brackets, like on image.
![image](https://github.com/user-attachments/assets/2902fc43-6c1d-4786-834c-adf0c0b47a31)

**Comment by darrenburns** [comment] 2024-11-18 17:01
I cannot reproduce that @pedroid999. Closing this issue as the original one is fixed - @pedroid999 if you're still having trouble please make a new issue.

**Closed by darrenburns** 2024-11-18 17:01 UTC
Labels: bug
